USE [master]
GO

/****** Object:  Database [HondaGHAC]    Script Date: 2018/12/29 16:55:33 ******/
CREATE DATABASE [HondaGHAC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBTAG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DBTAG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBTAG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DBTAG_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [HondaGHAC] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HondaGHAC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HondaGHAC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HondaGHAC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HondaGHAC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HondaGHAC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HondaGHAC] SET ARITHABORT OFF 
GO

ALTER DATABASE [HondaGHAC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HondaGHAC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HondaGHAC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HondaGHAC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HondaGHAC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HondaGHAC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HondaGHAC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HondaGHAC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HondaGHAC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HondaGHAC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HondaGHAC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HondaGHAC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HondaGHAC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HondaGHAC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HondaGHAC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HondaGHAC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HondaGHAC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HondaGHAC] SET RECOVERY FULL 
GO

ALTER DATABASE [HondaGHAC] SET  MULTI_USER 
GO

ALTER DATABASE [HondaGHAC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HondaGHAC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HondaGHAC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HondaGHAC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HondaGHAC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HondaGHAC] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HondaGHAC] SET  READ_WRITE 
GO

